{{- if eq .Values.environment "d" }}
kind: Build
apiVersion: build.openshift.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}-buildconfig
spec:
  nodeSelector: null
  output:
    to:
      kind: {{ .Values.buildConfigCreation.kind }}
      name: {{ .Values.buildConfigCreation.repository }}:{{ .Values.buildConfigCreation.tag }}
    pushSecret:
      name: {{ .Values.pullSecretName }}
  serviceAccount: builder
  resources: 
    limits:
      cpu: {{ .Values.resources.cpu }}
      memory: {{ .Values.resources.memory }}
    requests:
      cpu: {{ .Values.resources.cpu }}
      memory: {{ .Values.resources.memory }} 
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  strategy:
    type: Docker
    dockerStrategy: 
      pullSecret:
        name: artifactory-pullsecret
      noCache: true
      forcePull: true
      volumes:
        - name: jfrog-secret-volume
          mounts: 
            - destinationPath: /run/secrets/jfrog
          source:
            type: Secret
            secret:
              secretName: jfrog-services-secret
  source:
    type: Git
    git:
      uri: '{{ .Values.buildConfiguration.gitUri }}'
    contextDir: /{{ .Values.buildConfiguration.gitUri }}
    sourceSecret:
      name: {{ .Values.buildConfiguration.contextDir }}
  triggers:
    - type: {{ .Values.buildConfiguration.ConfigChange }}
  runPolicy: {{ .Values.buildConfiguration.Serial }}
{{- end }}
